### ISSUE TITLE
本地怎么跑不起来

### ISSUE THREAD

**Issue by comid** [yociduo/scrum-planning-poker#4]
你好，我把源码下载到本地发现跑不起来，缺少了数据库，我能要一份数据库文件么。还有，开发中不是用的微信小程序自带开发工具么，我运行前端提示没有app.json文件。

**Comment by yociduo** [comment]
前端需要运行npm run dev或者npm run build
小程序开发工具目录是指导client/dist/
后端需要使用MySql数据库，后端配置文件有.example.env，详细使用参考dotenv

**Comment by comid** [comment]
本地还是跑步起来。
首先，server 端：npm run dev, 数据库创建了，程序也监听3000 端口了。
然后，client 端：npm run dev 后，用微信开发工具指向 dist文件夹。微信小程序工具报错：
```
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'Promise' of undefined 
 TypeError: Cannot read property 'Promise' of undefined
    at http://127.0.0.1:34869/appservice/npm/wepy-async-function/index.js:14:7
    at require (http://127.0.0.1:34869/appservice/__dev__/WAService.js:1:971778)
    at http://127.0.0.1:34869/appservice/__dev__/WAService.js:1:971387
    at http://127.0.0.1:34869/appservice/app.js:23:1
    at require (http://127.0.0.1:34869/appservice/__dev__/WAService.js:1:971778)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:34869/appservice/appservice?t=1551430993569:1418:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:34869/appservice/appservice?t=1551430993569:1430:20)

```

如果：ctrl+c 停止server端，重新用npm run build 运行，程序就会报错。
难道每次重启都需要 drop database XX;  然后 create databse XX;才能运行后端么？
~~~~求解，本地还是跑步起来

**Comment by yociduo** [comment]
对于client端请参考，https://tencent.github.io/wepy/document.html#/?id=%E6%B7%BB%E5%8A%A0%E9%A1%B9%E7%9B%AE

**Comment by yociduo** [comment]
对于server端，如果有数据库的话不需要删除，直接跑就可以了

**Comment by comid** [comment]
根据你这次提供的信息，就差最后一步了（估计吧），目前前端请求报错：
~~~
secretOrPrivateKey must have a value
~~~
具体信息是：
~~~
{"name":"Error","message":"secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at Object.module.exports [as sign] (/Users/comid/Desktop/scrum-planning-poker/server/node_modules/jsonwebtoken/sign.js:107:20)\n    at UserRepository.sign (/Users/comid/Desktop/scrum-planning-poker/server/src/repository/UserRepository.ts:67:16)\n    at UserRepository.wxLogin (/Users/comid/Desktop/scrum-planning-poker/server/src/repository/UserRepository.ts:49:24)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
~~~
搜了搜，好像是 token相关的错。请问下，你们开发环境怎么解决这个问题的呢。谢谢

**Comment by yociduo** [comment]
`JWT_SECRET=secret`
这行有配置吗？在.env文件里

**Comment by comid** [comment]
这行就是不知道怎么配置了，有相关参考文档么？

**Comment by yociduo** [comment]
复制/server/.example.env文件到/server/.env

**Comment by comid** [comment]
复制/server/.example.env文件到/server/.env ? 
没看懂啥意思，“.env”是隐藏文件夹么？

**Comment by yociduo** [comment]
请参考：https://github.com/motdotla/dotenv

**Comment by comid** [comment]
> `JWT_SECRET=secret`
> 这行有配置吗？在.env文件里

这行，我应该配置啥呢？

**Comment by yociduo** [comment]
这行无所谓，主要把数据库链接什么的写对就行了
